### ISSUE TITLE
env command

### ISSUE THREAD

**Issue by KSXGitHub** [shelljs/shx#166] opened 2019-09-10 05:25 UTC
I wish to convert this verbose command:

```sh
cross-env FOO=foo BAR=bar shx command
```

to this:

```sh
shx env FOO=foo BAR=bar command
```

**Comment by nfischer** [comment] 2019-10-02 07:05
Can you give a concrete example? Most shelljs commands do not examine environmental variables, and it's not clear which case you're actually hitting.

**Comment by KSXGitHub** [comment] 2019-10-02 07:13
@nfischer I think you misunderstand.

> Most shelljs commands do not examine environmental variables

I don't need shelljs commands to read environment variables, I need a shelljs command that **sets** an environment variable and spawns a subprocess with that new environment variable (similar to UNIX's `env` command).

For example:

```sh
shx env FOO=foo BAR=bar node -p 'console.log(process.env.FOO, process.env.BAR)'
```

should print `foo bar`.

Also, UNIX's `env` without any arguments would print all environment variables (so yeah, it does read).

**Comment by nfischer** [comment] 2019-10-08 07:35
We only support executing ShellJS commands (so it wouldn't matter if we set env vars, those shelljs commands wouldn't use them for anything).

I believe this is a duplicate of #127.

**Closed by nfischer** 2019-10-08 07:35 UTC
Labels: duplicate
