### ISSUE TITLE
Proposal for adding `true` command

### ISSUE THREAD

**Issue by exKAZUu** [shelljs/shx#130] opened 2018-06-08 01:24 UTC
There is no `true` command on Windows. Although some workarounds exist, I feel `shx true` is convenient.

**Comment by nfischer** [comment] 2018-06-08 04:55
Thanks for the request! This is a duplicate of #105, so I'll close in favor of that issue. @exKAZUu could you provide some example use-cases on that issue?

**Closed by nfischer** 2018-06-08 04:55 UTC
Labels: duplicate, feat

**Comment by exKAZUu** [comment] 2018-06-10 00:18
@nfischer Sorry for making a duplicated issue.
In my use case, I'd like to use Windows-specific command like `mklink` on a cross-platform project and I'd like to use `true` command in my npm script in order to prevent errors on non-Windows environment.
Btw, the behavior of `mklink /d` and `ln -s` seems different. Is it expected? (So I need to use `mklink`)

**Comment by nfischer** [comment] 2018-06-11 17:42
@exKAZUu I'm not familiar with `mklink`, so I'm not sure if this is a bug in our end. Could you give examples for how `shx ln -s` and `mklink /d` differ?

**Comment by exKAZUu** [comment] 2018-06-12 02:42
@nfischer 
`shx ln -s` creates a junction link, in contrast, `mklink /d` creates a symbolic link.
However, I now notice `shx ln -s` is better than `mklink /d` in our use case. Sorry.

Btw, I've investigated the link mechanism on Windows.
For your reference, I'll explain the differences.

There are three kinds of links on Windows as follows. The third page summarizes them.
https://www.2brightsparks.com/resources/articles/NTFS-Hard-Links-Junctions-and-Symbolic-Links.pdf

Here is the current behavior of some commands.
- `shx ln -s` for a directory creates a junction link
- `mklink /d` for a directory creates a hard link
- `mklink /j` for a directory creates a junction link
- `mklink /s` for a directory creates a symbolic link
- `ln -s` using `Git for Winows` for a directory copies the directory (?)

**Comment by nfischer** [comment] 2018-06-12 18:11
@exKAZUu thanks! Yes, the junction link is intended behavior, this was merged into shelljs a long time ago (https://github.com/shelljs/shelljs/pull/87 and https://github.com/shelljs/shelljs/pull/104).
