### ISSUE TITLE
rsync

### ISSUE THREAD

**Issue by aminya** [shelljs/shx#183] opened 2020-06-06 06:45 UTC
Adding rsync would be nice

**Comment by nfischer** [comment] 2020-06-07 02:00
Are there particular features you need which `cp` doesn't offer?

**Comment by aminya** [comment] 2020-06-07 02:07
https://dev.to/wolfiton/difference-between-cp-and-rsync-dk3

**Comment by nfischer** [comment] 2020-06-07 05:34
Not sure if we can reach the same level of performance. `-p` option is tracked in https://github.com/shelljs/shelljs/issues/771. Let's consider this a duplicate of that issue for now.

**Closed by nfischer** 2020-06-07 05:34 UTC
Labels: duplicate, feat
