### ISSUE TITLE
Add ability to invert test

### ISSUE THREAD

**Issue by funnylookinhat** [shelljs/shx#202] opened 2022-06-27 18:39 UTC
Thank you for creating and maintaining this package - it is incredibly useful!

I've encountered a unique situation that I don't think is currently supported by shx (but it supported by shelljs).

I can test if a file or directory exists with the `test` command:

```
shx test -f "file"
shx test -d "directory"
```

But I cannot do the opposite (check if it does not exist).  ShellJS supports the negation of a test, but I'm not seeing a way to do it with shx.

https://github.com/shelljs/shelljs#testexpression

**Comment by nfischer** [comment] 2022-07-05 07:21
Looks like this could be a duplicate of issue #173?

**Closed by nfischer** 2022-07-05 07:21 UTC
Labels: duplicate, feat

**Comment by funnylookinhat** [comment] 2022-07-05 13:04
Ah yes - thank you for catching that.  Sorry for the duplicate issue. :-)
